# How many times in one day the message will be broadcast before
# stopping. So if a player logs on and off several times, the annoucement
# only happens this number of times. And only if the last message was made
# annoucment_interval minutes previously
maximum_announcements: 5

date_format:
  # Format used for parsing dates present in config file or from user input
  input: "MM-dd"
  
  # Format of dates when displaying them to the user
  output: "MMM dd"
  
# Allows players who join the server for the first time to get the 
# anniversary present
first_join_gift: false
